### PR TITLE
Master

### PR DESCRIPTION
**Pull request by waynebeaton**
Update master to include updates intended to bring this representation inline with the current release version.

### CODE REVIEW

**Comment by guw** [comment]
@waynebeaton The repo uses the `develop` branch as its main branch. From `develop` one should merge into `master` when released, i.e. published.

Should we get rid of this and just use `master`?

**Comment by waynebeaton** [comment]
The current configuration seems overly complex. I honestly don't expect to have very many contributions.

**Comment by guw** [comment]
I'll reduce it to just master.

**Comment by guw** [comment]
@waynebeaton I'm going to close this one. Once #8 is merged, I'll kill the `develop` branch.

**Pull request closed without merging**
